# Generated by Django 5.1.2 on 2024-10-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_user_id_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
